ALTER TABLE `AnalyticsEvent`
    MODIFY `eventType` ENUM('PAGE_VIEW', 'RESUME_DOWNLOAD', 'PROJECT_VIEW', 'PROJECT_DETAIL_VIEW', 'PROJECT_DEMO_CLICK', 'PROJECT_GITHUB_CLICK', 'GITHUB_CLICK', 'LINKEDIN_CLICK', 'EMAIL_CLICK', 'LANGUAGE_CHANGE', 'WHATSAPP_CLICK') NOT NULL;

CREATE TABLE `LoginRateLimit` (
    `key` CHAR(64) NOT NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `windowStart` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `blockedUntil` DATETIME(3) NULL,
    `updatedAt` DATETIME(3) NOT NULL,
    INDEX `LoginRateLimit_updatedAt_idx`(`updatedAt`),
    PRIMARY KEY (`key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
